version: '3.9'
services:
  nestapp:
    container_name: nestjsproject
    image: imagenestjsproject:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - my_network
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - my_network

volumes:
  pgdata: {}

networks:
  my_network:
    driver: bridge
